apiVersion: v1
kind: LimitRange
metadata:
  name: default-container-limit-range
  namespace: default
spec:
  limits:
  - default:
      memory: 100Mi
      cpu: 50m
    defaultRequest:
      memory: 10Mi
      cpu: 5m
    max:
      memory: 1000Mi
      cpu: 500m
    min:
      memory: 1Mi
      cpu: 1m
    type: Container
---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: default-resource-quota
  namespace: default
spec:
  hard:
    requests.cpu: 1
    requests.memory: 1Gi
    limits.cpu: 1
    limits.memory: 1Gi
    pods: 0
    services.nodeports: "0"
