apiVersion: v1
clusters:
- cluster:
    server: endpoint-url
    certificate-authority-data: base64-encoded-ca-cert
  name: kubernetes
contexts:
- context:
    cluster: kubernetes
    user: common-name
  name: common-name
current-context: common-name
kind: Config
preferences: {}
users:
- name: common-name
  user:
    exec:
      apiVersion: client.authentication.k8s.io/v1alpha1
      command: aws-iam-authenticator
      args:
        - "token"
        - "-i"
        - "cluster-name"
        - "-r"
        - "role-arn"
