apiVersion: v1
kind: LimitRange
metadata:
  name: ingestor-container-limit-range
  namespace: ingestor
spec:
  limits:
  - default:
      memory: 2000Mi
      cpu: 2
    defaultRequest:
      memory: 2000Mi
      cpu: 2
    max:
      memory: 8000Mi
      cpu: 4
    min:
      memory: 50Mi
      cpu: 10m
    type: Container
---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: ingestor-resource-quota
  namespace: ingestor
spec:
  hard:
    requests.cpu: 10
    requests.memory: 12Gi
    limits.cpu: 15
    limits.memory: 15Gi
    pods: 5
    services.nodeports: "0"
