apiVersion: policy/v1beta1
kind: PodDisruptionBudget
metadata:
  name: ingress-nginx
  namespace: kube-ingress
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: ingress-nginx 

---

apiVersion: policy/v1beta1
kind: PodDisruptionBudget
metadata:
  name: nginx-default-backend
  namespace: kube-ingress
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: nginx-default-backend
