apiVersion: v1
kind: LimitRange
metadata:
  name: prod-container-limit-range
  namespace: prod
spec:
  limits:
  - default:
      memory: 200Mi
      cpu: 0.2
    defaultRequest:
      memory: 100Mi
      cpu: 0.1
    max:
      memory: 500Mi
      cpu: 1
    min:
      memory: 5Mi
      cpu: 0.05
    type: Container
---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: prod-resource-quota
  namespace: prod
spec:
  hard:
    requests.cpu: 30
    requests.memory: 30Gi
    limits.cpu: 50
    limits.memory: 50Gi
    pods: 100
    services.nodeports: "0"
