apiVersion: v1
kind: LimitRange
metadata:
  name: test-container-limit-range
  namespace: test
spec:
  limits:
  - default:
      memory: 100Mi
      cpu: 50m
    defaultRequest:
      memory: 10Mi
      cpu: 5m
    max:
      memory: 1000Mi
      cpu: 500m
    min:
      memory: 1Mi
      cpu: 1m
    type: Container
---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: test-resource-quota
  namespace: test
spec:
  hard:
    requests.cpu: 10
    requests.memory: 10Gi
    limits.cpu: 15
    limits.memory: 15Gi
    pods: 25
    services.nodeports: "0"
