apiVersion: rbac.authorization.k8s.io/v1beta1
kind: Role
metadata:
 name: discover-tiller
 namespace: kube-system
rules:
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - list
- apiGroups:
  - ""
  resources:
  - pods/portforward
  verbs:
  - create
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: discover-tiller
  namespace: kube-system
roleRef:
  kind: Role
  name: discover-tiller
  apiGroup: rbac.authorization.k8s.io
subjects:
- apiGroup: rbac.authorization.k8s.io
  kind: User
  name: dev
  namespace: dev
- apiGroup: rbac.authorization.k8s.io
  kind: User
  name: test
  namespace: test
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: Role
metadata:
 name: tiller-bookkeeping
 namespace: kube-system
rules:
- apiGroups:
  - ""
  resources:
  - configmaps
  verbs:
  - create
  - delete
  - deletecollection
  - get
  - list
  - patch
  - update
  - watch
---
# below will let tiller to operate on any given namespace provider correct k8s rbac enabled.
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: tiller-edit
  namespace: kube-system
roleRef:
  kind: ClusterRole
  name: edit
  apiGroup: rbac.authorization.k8s.io
subjects:
- kind: ServiceAccount
  name: tiller
  namespace: kube-system
