apiVersion: v1
kind: Service
metadata:
  name: istio-ingressgateway
  namespace: istio-system
  annotations:
    # make it http if you want https and http in play
    service.beta.kubernetes.io/aws-load-balancer-backend-protocol: "http"
    # Increase the ELB idle timeout to avoid issues with WebSockets or Server-Sent Events.
    service.beta.kubernetes.io/aws-load-balancer-connection-idle-timeout: "3600"
    # put your AWS SSL cert ARN here
    service.beta.kubernetes.io/aws-load-balancer-ssl-cert: ARN
    service.beta.kubernetes.io/aws-load-balancer-ssl-ports: "https"