apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUN5RENDQWJDZ0F3SUJBZ0lCQURBTkJna3Foa2lHOXcwQkFRc0ZBREFWTVJNd0VRWURWUVFERXdwcmRXSmwKY201bGRHVnpNQjRYRFRFNU1ERXlNakEwTlRBek5Gb1hEVEk1TURFeE9UQTBOVEF6TkZvd0ZURVRNQkVHQTFVRQpBeE1LYTNWaVpYSnVaWFJsY3pDQ0FTSXdEUVlKS29aSWh2Y05BUUVCQlFBRGdnRVBBRENDQVFvQ2dnRUJBTGdMCmxwWWE0RjE2aWdxYUtiYUEzWk5XOHQxY3FGY0xmOGtubXFNRU0vQlFBUEVRYTM5NzFPVlc4bnJpUENCcjI5YkwKZ0U0cDdYeC8rYlpUcEtpRmwzY2RUbTZ3RytlZFJrUzZsWm91N1laeTNtblN4QW5XMmpldlMxUnRqZi9LQTkycQo2Tk9TZHBoaDhySUxDWDdMQXR4ekdJbXJxTnFSZ04yVjVOdUZCQVFNSnZvSWh2eU9mMU9rNWw5STdFSGM0TGVNCkI2VFBwa0s1Y0RaNnhRUDNnVFRZMnZUM0ZLejYrOUhDQnVVeGJEN0w1Mys3dW14bnNpNUpiNGRldkVXWmcrNkMKZmcxTFcyeHpYQlZySlBMNkJqTkJ3M1pxQXpNcGhjMXAvc3VlNDFaN0hlYk05T2p6L2pjVXovbFlpbUZEclNLcApYbXB1ZGtSU1pHTDJkY3kzLzdNQ0F3RUFBYU1qTUNFd0RnWURWUjBQQVFIL0JBUURBZ0trTUE4R0ExVWRFd0VCCi93UUZNQU1CQWY4d0RRWUpLb1pJaHZjTkFRRUxCUUFEZ2dFQkFKbElxdm42cHJMc3RzdFhycW5NTW9NZjYxcEwKL3VETVk1eEpwTGtubEI0bnJxY093OW8xeDE0eDBUdWphei93cmt1T3RwQWt0VjlveTlTc0lpNlZ2UGovckRSUwpWVU9yMXIvQlBpenl3dXlYRmJUODV0bWM3bjJjVHZDdHRZMXUvMzFWNEIzd0FwVTQ1cU1FOEpmVUNLaExBS3owCjZ4cEx1c1gvTmZpTnVUcTRsT05pTVpOZVhldDVHV2VLRmZqZDU4cElCU1lZMkR1OGNkdE8xRkxsSXBSbUFUQ0UKaU1nelc0YVhFTzZqV0kyOXlxZ2lwOE52MEIyQjBrcDBLUS9iUnJ1RzJCWExzRFdhM1VQRG9mYWs3SGxXRWpxQQo1VmFxU1NvRDF2anhSWVJjVzUraEFQcGVXanphQk8xclpOME9rMjNQd1JadVFSTkxtbmw5NTNJZFI4ST0KLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQo=
    server: https://B448C9848F0CFC63B3653E5D2B954802.sk1.us-east-2.eks.amazonaws.com
  name: prageethw-1548132216.us-east-2.eksctl.io
- cluster:
    certificate-authority-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUN5RENDQWJDZ0F3SUJBZ0lCQURBTkJna3Foa2lHOXcwQkFRc0ZBREFWTVJNd0VRWURWUVFERXdwcmRXSmwKY201bGRHVnpNQjRYRFRFNU1ERXlNakExTWpjMU0xb1hEVEk1TURFeE9UQTFNamMxTTFvd0ZURVRNQkVHQTFVRQpBeE1LYTNWaVpYSnVaWFJsY3pDQ0FTSXdEUVlKS29aSWh2Y05BUUVCQlFBRGdnRVBBRENDQVFvQ2dnRUJBTThVCmJLQjk4KzNxbjUyTm9EWHB3UGJvbkZCQkJLYlk1Z2FtRDhmUkU1dTVKN1VlZlQ5T0dOa25pTE1yTExjK2xmakgKdW03SGxOQ0ZQdFc2Q1cvQzBEdFZaOStPenViSnlnNkpVK1R1MERUdEZJYmtzVUp4MllaZmZ0cjVwcGxJa3B6WApyVmMzYkZiaG9kNXJlbTI2N2JMZGpYUzdZc1Q1dG02N01udGlaaitYNHNEdWg3RHEzNmVRWW9EL1ZiUmN4WllHCmlIY2dCSWFjSnhLSUZIODY0ckVlbklxYS91Y3N6eWpRUmpJMGtTS2pxdWVlNGlvT3podDZscFdRN21QMlU2KzAKVHZQK2xzNlU0c3pPUVJFLzFqWXJMd2UxUHRFRDhUcFkwd1RlM0tDSG9tVi9QcFE0SEt0UHc1USs5eHd0YmZ4agpWcUErbGZTSWVRSUl3UlNhTTdFQ0F3RUFBYU1qTUNFd0RnWURWUjBQQVFIL0JBUURBZ0trTUE4R0ExVWRFd0VCCi93UUZNQU1CQWY4d0RRWUpLb1pJaHZjTkFRRUxCUUFEZ2dFQkFKSmZ6YmZDTEJpUnBPTk5makdqcmQwb0ZyYnYKTEpob2tvYlNYaUs3bVdHT2VLajNYY1B2alpoelFzUGYxTlE1cHBIMTMza3NiRmNDZFB5Lzdmb0FJdXdSeHprawpjNy85QllZR3hIQndCUFdKcEs2MCtRVW9uY0wwYjhUQVROK2o0Z3UxYmlhSTlxUEh5WVBWM1I1dlpzRXdneTFzCkgzWlpwUzVLMGg1M1NIZGcxQWRPbUk4eW9yakc5SG9HR3dRTkNzT1NSTzlTM0hCSWN4NTFzQmNVZDVPMkJtOWsKc3JLMjh6K1Eyb1ZLMnJGb0t5aFVYVDVrUktZQjd3VzB0RSt1UGxFU2hrelFyMmxpVDhNYW9iMk9hU2FWSndueQpFWC9CQkllWS9yZDYwV3hkTlo0Qk5vUldCdWJIaXJ6QXBMQkhnellxbVBMNU0vTnpsMms0Y3RuS0h1WT0KLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQo=
    server: https://8F2A1274DC0A9CC3DC33775FE9856DDF.yl4.us-east-2.eks.amazonaws.com
  name: prageethw-1548134438.us-east-2.eksctl.io
contexts:
- context:
    cluster: prageethw-1548132216.us-east-2.eksctl.io
    user: prageeth@prageethw-1548132216.us-east-2.eksctl.io
  name: prageeth@prageethw-1548132216.us-east-2.eksctl.io
- context:
    cluster: prageethw-1548134438.us-east-2.eksctl.io
    user: prageeth@prageethw-1548134438.us-east-2.eksctl.io
  name: prageeth@prageethw-1548134438.us-east-2.eksctl.io
current-context: prageeth@prageethw-1548134438.us-east-2.eksctl.io
kind: Config
preferences: {}
users:
- name: prageeth@prageethw-1548132216.us-east-2.eksctl.io
  user:
    exec:
      apiVersion: client.authentication.k8s.io/v1alpha1
      args:
      - token
      - -i
      - prageethw-1548132216
      command: aws-iam-authenticator
      env: null
- name: prageeth@prageethw-1548134438.us-east-2.eksctl.io
  user:
    exec:
      apiVersion: client.authentication.k8s.io/v1alpha1
      args:
      - token
      - -i
      - prageethw-1548134438
      command: aws-iam-authenticator
      env: null
